### ISSUE TITLE
slotResized's detail shall be more informative

### ISSUE THREAD

**Issue by max-scopp** [alesgenova/split-me#1]
From your feedback from Slack, I'd suggest making an issue.

To stick with the nth's being scaled by percentage like [Split.js](https://github.com/nathancahill/Split.js/#saving-state) does is generally not a bad idea. There _should_ be no need to return the index of the divider since you can still differentiate them by assigning their specific handlers.

Personally, I would like a whole object which may be better to maintain. I would also consider extending the event with an `originalEvent` property in order to detect different behaviors (e.g. touch).

I guess if you're using a lot of instances, people may be better off to use an `id` instead of an index. That way, you can still re-acquire the NodeElement without much overhead. But I don't have a preference here, just some thoughts. Maybe declaring the divider with an provided `id`, only otherwise using an index since there will be no other way to make it unique.

Like this:

```
CustomEvent {
  detail: {
    sizes: [0.25, 0.75],
    divider: number | NodeElement | "id"
  },
  originalEvent: MouseEvent | TouchEvent
}
```

Let me know you what you think.

**Comment by alesgenova** [comment]
@max-scopp 
Thank you for the detailed suggestion!
I have opened a pull request implementing most of what you suggest.
If you spare a few minutes you can review it before merging it, to make sure it serves your needs

**Comment by max-scopp** [comment]
Looks lovely!

I've seen you simply added the host as `splitter`, in remorse, I think we don't need that since there already is `srcElement`, `target` and `path`..

I've also made a pull request for the README: https://github.com/alesgenova/split-me/pull/3
