### ISSUE TITLE
Add a css variable for the phantom-divider thickness

### ISSUE THREAD

**Issue by scottlepp** [alesgenova/split-me#6]
When setting the divider-thickness, the phantom-divider still remains wider, and the drag handle may overlap content to the right (if the split is vertical).  It would be nice if we could reduce the drag handle width.  

Also, if the split is vertical, and the left item is set to overflow auto/scroll, the phantom-divider (drag handle) overlaps the scrollbar and you can't scroll.

**Comment by alesgenova** [comment]
Thank you for reporting the issue!
#7 exposes a css variable to tweak the width of the phantom dividers.
It doesn't address the overlapping of the scrollbar, but it should mitigate the issue when setting appropriate values.
Also, not the phantom divider only extends as much as the actual divider (before it used to span the entire length no matter what)

Let me know if you have additional suggestion for that pull request, if not I will merge it and tag a new release soon

**Comment by scottlepp** [comment]
@alesgenova looks good.  Thanks!

**Comment by alesgenova** [comment]
The fix is live in `1.1.8` on npm!
